"use client";
import { useApp } from "@/components/app-provider";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

export default function ProfilePage() {
  const { data, currentUser, logout, reset, markNoticesRead } = useApp(); const router = useRouter();
  useEffect(() => { if (!currentUser) router.replace("/login"); }, [currentUser, router]);
  if (!currentUser || !data) return <main className="page text-center text-slate-500">正在加载…</main>;
  const notices = data.notifications.filter((n) => n.userId === currentUser.id); const unread = notices.filter((n) => !n.read).length; const published = data.activities.filter((a) => a.creatorId === currentUser.id).length; const joined = data.activities.filter((a) => a.memberIds.includes(currentUser.id)).length;
  async function restore() { if (confirm("恢复后会清除你在此浏览器中新增的账号、活动和申请，确定继续吗？")) { await reset(); router.push("/login"); } }
  return <main className="page max-w-3xl"><section className="card bg-gradient-to-br from-indigo-600 to-brand text-white"><p className="text-sm text-indigo-100">我的校园名片</p><div className="mt-3 flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-3xl bg-white/20 text-3xl font-black">{currentUser.nickname.slice(0, 1)}</span><div><h1 className="text-2xl font-black">{currentUser.nickname}</h1><p className="mt-1 text-indigo-100">{currentUser.college} · {currentUser.grade}</p></div></div><div className="mt-5 flex flex-wrap gap-2">{currentUser.interests.length ? currentUser.interests.map((x) => <span className="tag bg-white/15 text-white" key={x}>{x}</span>) : <span className="text-sm text-indigo-100">还未设置兴趣标签</span>}</div></section><section className="mt-5 grid grid-cols-3 gap-3">{[["发布活动", published], ["参与活动", joined], ["未读通知", unread]].map(([label, value]) => <div className="card p-4 text-center" key={String(label)}><p className="text-2xl font-black text-brand">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>)}</section><section className="card mt-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black text-ink">通知中心</h2><p className="mt-1 text-sm text-slate-500">申请、审批和活动变更都会出现在这里。</p></div>{unread > 0 && <button className="btn-soft py-2" onClick={markNoticesRead}>全部已读</button>}</div><div className="mt-4 space-y-2">{notices.length ? notices.slice(0, 12).map((n) => <div key={n.id} className={`rounded-2xl p-3 text-sm ${n.read ? "bg-slate-50 text-slate-500" : "bg-lavender text-indigo-800"}`}><div className="flex justify-between gap-3"><span>{n.content}</span>{!n.read && <i className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-brand" />}</div><p className="mt-1 text-xs opacity-60">{new Date(n.createdAt).toLocaleString("zh-CN")}</p></div>) : <p className="rounded-2xl bg-slate-50 p-5 text-center text-sm text-slate-500">暂时没有通知，去发现页寻找新活动吧。</p>}</div></section><section className="card mt-5"><h2 className="text-lg font-black text-ink">演示数据与账户</h2><p className="mt-2 text-sm leading-6 text-slate-500">本版本仅用于课堂演示，账号和所有活动数据只保存在当前浏览器。本地密码使用摘要保存，但不具备正式账号系统的安全能力。</p><div className="mt-4 flex flex-wrap gap-3"><button className="btn-danger" onClick={restore}>恢复演示数据</button><button className="btn-soft" onClick={() => { logout(); router.push("/login"); }}>退出登录</button></div></section></main>;
}
