"use client";
import { useApp } from "@/components/app-provider";
import { UserAvatar } from "@/components/user-avatar";
import { systemAvatars } from "@/lib/avatars";
import Link from "next/link";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const avatarClasses = { indigo: "bg-indigo-500", emerald: "bg-emerald-500", orange: "bg-orange-500", rose: "bg-rose-500" };
const creditRules = [
  ["新账号初始分", "100 分"],
  ["发布活动", "+3"],
  ["活动按时完成", "成员 +2"],
  ["完成后收到 5 星评价", "+2"],
  ["完成后收到 4 星评价", "+1"],
  ["完成后收到 3 星评价", "不变"],
  ["完成后收到 1-2 星评价", "-2"],
  ["开始前 24 小时内退出", "-2"],
  ["开始前 24 小时内取消", "发起人 -3"],
] as const;

export default function ProfilePage() {
  const { data, currentUser, logout, reset, markNoticesRead, updateProfile, updateSettings, importData } = useApp(); const router = useRouter();
  const [editing, setEditing] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState("");
  const [showCreditRules, setShowCreditRules] = useState(false);
  const [form, setForm] = useState({ nickname: "", college: "", grade: "", interests: "", bio: "", avatarTone: "indigo" as keyof typeof avatarClasses, avatarUrl: "" });
  useEffect(() => { if (!currentUser) router.replace("/login"); else setForm({ nickname: currentUser.nickname, college: currentUser.college, grade: currentUser.grade, interests: currentUser.interests.join("，"), bio: currentUser.bio, avatarTone: currentUser.avatarTone, avatarUrl: currentUser.avatarUrl ?? "" }); }, [currentUser, router]);
  if (!currentUser || !data) return <main className="page text-center text-slate-500">正在加载…</main>;
  const appData = data;
  const user = currentUser;
  const previewUser = { ...currentUser, nickname: form.nickname || currentUser.nickname, avatarTone: form.avatarTone, avatarUrl: form.avatarUrl };
  const notices = data.notifications.filter((item) => item.userId === currentUser.id); const unread = notices.filter((item) => !item.read).length;
  const published = data.activities.filter((item) => item.creatorId === currentUser.id); const joined = data.activities.filter((item) => item.memberIds.includes(currentUser.id)); const completed = joined.filter((item) => item.status === "finished").length;
  const rate = joined.length ? Math.round(completed / joined.length * 100) : 0; const credits = data.creditLogs.filter((item) => item.userId === currentUser.id).slice(0, 5);
  const receivedEvaluations = data.evaluations.filter((item) => item.revieweeId === currentUser.id);
  const averageRating = receivedEvaluations.length ? (receivedEvaluations.reduce((sum, item) => sum + item.rating, 0) / receivedEvaluations.length).toFixed(1) : "暂无";
  const achievements = [published.length > 0 && "活动发起人", joined.length >= 2 && "校园同行者", currentUser.interests.length >= 3 && "兴趣探索家", currentUser.bio && currentUser.preferredCategories.length && "资料完善者", receivedEvaluations.some((item) => item.rating === 5) && "五星同行者"].filter(Boolean) as string[];
  const reviewVisibleCount = Object.values(currentUser.applicationProfileVisibility).filter(Boolean).length;
  function change(key: keyof typeof form, value: string) { setForm((item) => ({ ...item, [key]: value })); }
  function save(event: FormEvent) { event.preventDefault(); try { updateProfile({ ...form, interests: form.interests.split(/[，,]/).map((item) => item.trim()).filter(Boolean) }); setEditing(false); setSaved("个人资料已保存"); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } }
  function uploadAvatar(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; if (!file) return;
    if (!file.type.startsWith("image/")) { setError("请选择图片文件"); event.target.value = ""; return; }
    if (file.size > 1024 * 1024) { setError("头像图片请控制在 1MB 以内"); event.target.value = ""; return; }
    const reader = new FileReader();
    reader.onload = () => { change("avatarUrl", String(reader.result)); setError(""); };
    reader.readAsDataURL(file); event.target.value = "";
  }
  function toggleProfileVisible() { updateSettings({ notificationPreferences: user.notificationPreferences, profileVisible: !user.profileVisible, applicationProfileVisibility: user.applicationProfileVisibility, preferredCategories: user.preferredCategories, availability: user.availability }); setSaved(!user.profileVisible ? "个人主页已切换为公开" : "个人主页已切换为私密"); setError(""); }
  async function restore() { if (confirm("恢复后会清除本浏览器中的演示改动，确定继续吗？")) { await reset(); router.push("/login"); } }
  function exportData() { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); link.download = `campusmate-demo-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); }
  function importFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { importData(String(reader.result)); setSaved("演示数据已导入"); } catch (reason) { setError(reason instanceof Error ? reason.message : "导入失败"); } }; reader.readAsText(file); event.target.value = ""; }
  function notificationPreview(item: (typeof notices)[number]) {
    const activityExists = item.activityId && appData.activities.some((activity) => activity.id === item.activityId);
    const className = "mt-2 block rounded-xl bg-slate-50 p-3 text-sm";
    return activityExists ? <Link className={className} href={`/activity/${item.activityId}`} key={item.id}>{item.content}</Link> : <p className={className} key={item.id}>{item.content}</p>;
  }
  return <main className="page max-w-3xl"><section className="card bg-gradient-to-br from-indigo-600 to-brand text-white"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-indigo-100">我的校园名片</p><div className="mt-3 flex items-center gap-4"><UserAvatar user={currentUser} size="h-16 w-16 text-3xl" /><div><h1 className="text-2xl font-black">{currentUser.nickname}</h1><p className="mt-1 text-indigo-100">{currentUser.college} · {currentUser.grade}</p></div></div></div><button className="btn bg-white/15 text-white hover:bg-white/25" onClick={() => setEditing((item) => !item)}>{editing ? "取消编辑" : "编辑资料"}</button></div><p className="mt-4 text-sm text-indigo-50">{currentUser.bio || "用一句话介绍自己，让同学更容易找到你。"}</p></section>
    <section className="card mt-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black text-ink">主页公开状态：{currentUser.profileVisible ? "公开" : "私密"}</h2><p className="mt-1 text-sm text-slate-500">{currentUser.profileVisible ? "活动成员可以看到你的学院、年级和兴趣标签。" : "其他同学只能看到你的昵称和基础名片。"}</p><p className="mt-1 text-xs text-slate-400">申请活动时另有独立授权，目前允许发起人查看 {reviewVisibleCount} 项资料。</p></div><button className={currentUser.profileVisible ? "btn-danger" : "btn-primary"} onClick={toggleProfileVisible}>{currentUser.profileVisible ? "切换为私密" : "切换为公开"}</button></div></section>
    {editing && <form className="card mt-5 grid gap-4 sm:grid-cols-2" onSubmit={save}><div className="sm:col-span-2"><label className="label">头像图片</label><div className="mt-2 flex flex-wrap items-center gap-3"><UserAvatar user={previewUser} size="h-16 w-16 text-2xl" /><label className="btn-soft cursor-pointer">上传图片<input className="hidden" type="file" accept="image/*" onChange={uploadAvatar} /></label><button className="btn-soft" type="button" onClick={() => change("avatarUrl", "")}>使用首字母头像</button></div><p className="mt-2 text-xs text-slate-400">上传图片只保存在当前浏览器演示数据中，建议小于 1MB。</p><div className="mt-3 flex flex-wrap gap-2">{systemAvatars.map((avatar) => <button aria-label={`选择${avatar.label}`} className={`rounded-2xl border-2 p-1 ${form.avatarUrl === avatar.url ? "border-indigo-500" : "border-transparent"}`} key={avatar.id} onClick={() => change("avatarUrl", avatar.url)} type="button"><img alt={avatar.label} className="h-12 w-12 rounded-xl object-cover" src={avatar.url} /></button>)}</div></div><div><label className="label" htmlFor="nickname">昵称</label><input id="nickname" className="field" required value={form.nickname} onChange={(event) => change("nickname", event.target.value)} /></div><div><label className="label" htmlFor="college">学院</label><input id="college" className="field" required value={form.college} onChange={(event) => change("college", event.target.value)} /></div><div><label className="label">头像颜色</label><select className="field" value={form.avatarTone} onChange={(event) => change("avatarTone", event.target.value)}>{Object.keys(avatarClasses).map((item) => <option key={item} value={item}>{item}</option>)}</select></div><div><label className="label">兴趣标签</label><input className="field" value={form.interests} onChange={(event) => change("interests", event.target.value)} /></div><div className="sm:col-span-2"><label className="label">个人简介</label><textarea className="field min-h-24" maxLength={120} value={form.bio} onChange={(event) => change("bio", event.target.value)} /></div><button className="btn-primary sm:col-span-2">保存资料</button></form>}
    {(saved || error) && <p className={`mt-4 rounded-xl p-3 text-sm ${error ? "bg-rose-50 text-rose-600" : "bg-emerald-50 text-emerald-700"}`}>{error || saved}</p>}
    <section className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["发布活动", published.length], ["参与活动", joined.length], ["完成率", `${rate}%`], ["信用分", currentUser.creditScore]].map(([label, value]) => <div className="card p-4 text-center" key={String(label)}><p className="text-2xl font-black text-brand">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>)}</section>
    <section className="card mt-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-black text-ink">完成评价</h2><p className="mt-1 text-sm text-slate-500">活动结束后，成员可以互评。评价会进入信用记录，并帮助发起人判断协作可靠度。</p></div><div className="rounded-2xl bg-amber-50 px-4 py-2 text-center text-amber-700"><p className="text-xl font-black">{averageRating}</p><p className="text-xs">平均评分</p></div></div><div className="mt-4 space-y-3">{receivedEvaluations.length ? receivedEvaluations.slice(0, 4).map((evaluation) => { const activity = data.activities.find((item) => item.id === evaluation.activityId); const reviewer = data.users.find((item) => item.id === evaluation.reviewerId); return <div className="rounded-2xl bg-slate-50 p-3" key={evaluation.id}><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-bold text-ink">{activity?.title ?? "未知活动"}</p><span className="tag bg-amber-50 text-amber-700">{evaluation.rating} 星</span></div><p className="mt-1 text-xs text-slate-500">来自 {reviewer?.nickname ?? "未知同学"} · {evaluation.tags.join(" · ") || "未选择标签"}</p>{evaluation.comment && <p className="mt-2 text-sm text-slate-600">{evaluation.comment}</p>}</div>; }) : <p className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">完成活动并收到成员评价后，会显示在这里。</p>}</div></section>
    <section className="card mt-5"><button className="flex w-full items-center justify-between gap-4 text-left" onClick={() => setShowCreditRules((value) => !value)} type="button"><span><span className="text-lg font-black text-ink">信用分规则说明</span><span className="mt-1 block text-sm text-slate-500">默认收起，展开后查看信用分加减规则。</span></span><span className="text-xl font-black text-brand">{showCreditRules ? "−" : "+"}</span></button>{showCreditRules && <><p className="mt-4 text-sm text-slate-500">信用分用于课堂演示中的可靠度展示，不等同于真实信用评价。每条变动都会写入下方信用记录。</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{creditRules.map(([label, value]) => <div className="rounded-2xl bg-slate-50 p-3" key={label}><p className="text-sm font-bold text-ink">{label}</p><p className={`mt-1 text-lg font-black ${value.startsWith("-") ? "text-rose-600" : value.includes("+") ? "text-emerald-600" : "text-slate-500"}`}>{value}</p></div>)}</div></>}</section>
    <section className="card mt-5"><h2 className="text-lg font-black text-ink">偏好、成就与信用记录</h2><p className="mt-2 text-sm text-slate-500">{currentUser.preferredCategories.join(" · ") || "暂未设置偏好"} · {currentUser.availability}</p><div className="mt-3 flex flex-wrap gap-2">{achievements.map((item) => <span className="tag bg-amber-50 text-amber-700" key={item}>✦ {item}</span>)}</div><div className="mt-4 space-y-2">{credits.length ? credits.map((item) => <p className="rounded-xl bg-slate-50 p-2 text-sm" key={item.id}><b className={item.change >= 0 ? "text-emerald-600" : "text-rose-600"}>{item.change >= 0 ? "+" : ""}{item.change}</b> · {item.reason}</p>) : <p className="text-sm text-slate-500">完成、发起活动或收到评价后会留下信用记录。</p>}</div></section>
    <section className="card mt-5"><h2 className="text-lg font-black text-ink">活动历史</h2><div className="mt-3 space-y-2">{joined.slice(0, 5).map((activity) => <Link className="block rounded-xl bg-slate-50 p-3" href={`/activity/${activity.id}`} key={activity.id}>{activity.title} · {activity.status}</Link>)}</div></section>
    <section className="card mt-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black text-ink">通知中心</h2><p className="mt-1 text-sm text-slate-500">未读 {unread} 条</p></div><div className="flex gap-2">{unread > 0 && <button className="btn-soft py-2" onClick={markNoticesRead}>全部已读</button>}<Link className="btn-soft py-2" href="/notifications">查看全部</Link></div></div>{notices.slice(0, 3).map(notificationPreview)}</section>
    <section className="card mt-5"><h2 className="text-lg font-black text-ink">演示数据与账户</h2><div className="mt-4 flex flex-wrap gap-3"><Link className="btn-soft" href="/settings">通知与隐私设置</Link><Link className="btn-soft" href="/admin">举报处理演示</Link><button className="btn-soft" onClick={exportData}>导出数据 JSON</button><label className="btn-soft cursor-pointer">导入数据 JSON<input className="hidden" type="file" accept="application/json" onChange={importFile} /></label><button className="btn-danger" onClick={restore}>恢复演示数据</button><button className="btn-soft" onClick={() => { logout(); router.push("/login"); }}>退出登录</button></div></section></main>;
}
