"use client";
import { useApp } from "@/components/app-provider";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";

export default function RegisterPage() {
  const { register } = useApp(); const router = useRouter(); const [form, setForm] = useState({ nickname: "", college: "", grade: "大一", interests: "", password: "", confirm: "" }); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  const change = (key: keyof typeof form, value: string) => setForm((x) => ({ ...x, [key]: value }));
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); if (form.password.length < 6) return setError("密码至少需要 6 位"); if (form.password !== form.confirm) return setError("两次输入的密码不一致"); setSubmitting(true); try { await register({ nickname: form.nickname, college: form.college, grade: form.grade, interests: form.interests.split(/[，,]/).map((x) => x.trim()).filter(Boolean), password: form.password }); router.replace("/"); } catch (err) { setError(err instanceof Error ? err.message : "注册失败"); } finally { setSubmitting(false); } }
  return <main className="page max-w-lg"><section className="card mt-4"><h1 className="text-2xl font-black text-ink">创建你的校园名片</h1><p className="mt-2 text-sm text-slate-500">这是本地演示账号，仅保存在当前浏览器中。</p><form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><div><label className="label">昵称</label><input className="field" value={form.nickname} onChange={(e) => change("nickname", e.target.value)} required /></div><div><label className="label">学院</label><input className="field" value={form.college} onChange={(e) => change("college", e.target.value)} required /></div><div><label className="label">年级</label><select className="field" value={form.grade} onChange={(e) => change("grade", e.target.value)}>{["大一", "大二", "大三", "大四", "研究生"].map((x) => <option key={x}>{x}</option>)}</select></div><div><label className="label">兴趣标签</label><input className="field" placeholder="如：摄影，跑步" value={form.interests} onChange={(e) => change("interests", e.target.value)} /></div><div><label className="label">密码</label><input className="field" type="password" value={form.password} onChange={(e) => change("password", e.target.value)} required /></div><div><label className="label">确认密码</label><input className="field" type="password" value={form.confirm} onChange={(e) => change("confirm", e.target.value)} required /></div>{error && <p className="sm:col-span-2 rounded-xl bg-rose-50 p-3 text-sm text-rose-600">{error}</p>}<button disabled={submitting} className="btn-primary sm:col-span-2">{submitting ? "正在创建…" : "创建并进入 CampusMate"}</button></form><p className="mt-5 text-center text-sm text-slate-500">已有账号？ <Link className="font-bold text-brand" href="/login">去登录</Link></p></section></main>;
}
