"use client";
import { useApp } from "@/components/app-provider";
import { Empty } from "@/components/empty";
import { useParams, useRouter } from "next/navigation";
import { FormEvent, useState } from "react";

const tone: Record<string, string> = { "自习搭子": "bg-sky-50 text-sky-600", "运动搭子": "bg-emerald-50 text-emerald-600", "饭搭子": "bg-orange-50 text-orange-600", "比赛搭子": "bg-violet-50 text-violet-600", "游戏搭子": "bg-rose-50 text-rose-600", "兴趣活动": "bg-amber-50 text-amber-600" };
export default function ActivityDetailPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const { data, currentUser, apply, exitActivity, cancelActivity } = useApp(); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const activity = data?.activities.find((a) => a.id === params.id);
  if (!data) return <main className="page">正在加载…</main>;
  if (!activity) return <main className="page"><Empty title="活动不存在" description="它可能已被恢复演示数据时清除。" /></main>;
  const activityId = activity.id;
  const creator = data.users.find((u) => u.id === activity.creatorId); const members = activity.memberIds.map((id) => data.users.find((u) => u.id === id)).filter(Boolean); const free = activity.maxMembers - activity.memberIds.length;
  const application = currentUser ? data.applications.find((a) => a.activityId === activity.id && a.applicantId === currentUser.id && a.status !== "withdrawn") : undefined;
  const isMember = currentUser ? activity.memberIds.includes(currentUser.id) : false; const isCreator = currentUser?.id === activity.creatorId;
  function submit(e: FormEvent) { e.preventDefault(); try { apply(activityId, message); setMessage(""); } catch (err) { setError(err instanceof Error ? err.message : "申请失败"); } }
  function leave() { if (confirm("确认退出该活动吗？")) { try { exitActivity(activityId); } catch (err) { setError(err instanceof Error ? err.message : "退出失败"); } } }
  function cancel() { if (confirm("确认取消活动？所有成员都会收到通知。")) { try { cancelActivity(activityId); router.push("/my-team"); } catch (err) { setError(err instanceof Error ? err.message : "取消失败"); } } }
  return <main className="page max-w-4xl"><button className="mb-4 text-sm font-bold text-slate-500" onClick={() => router.back()}>← 返回活动列表</button><div className="grid gap-5 lg:grid-cols-[1.55fr_.85fr]"><section className="card"><div className="flex flex-wrap justify-between gap-3"><span className={`tag ${tone[activity.category]}`}>{activity.category}</span><span className={activity.status === "cancelled" ? "tag bg-slate-100 text-slate-500" : "tag bg-emerald-50 text-emerald-600"}>{activity.status === "cancelled" ? "活动已取消" : `还差 ${Math.max(free, 0)} 人`}</span></div><h1 className="mt-4 text-3xl font-black text-ink">{activity.title}</h1><p className="mt-5 whitespace-pre-wrap leading-7 text-slate-600">{activity.description}</p><div className="mt-7 grid gap-3 rounded-2xl bg-lavender p-4 text-sm text-indigo-900 sm:grid-cols-3"><p><b>◷ 时间</b><br />{new Date(activity.startTime).toLocaleString("zh-CN", { month: "long", day: "numeric", weekday: "short", hour: "2-digit", minute: "2-digit" })}</p><p><b>⌖ 地点</b><br />{activity.location}</p><p><b>◉ 成员</b><br />{activity.memberIds.length} / {activity.maxMembers} 人</p></div><div className="mt-5 flex flex-wrap gap-2">{activity.tags.map((tag) => <span key={tag} className="tag bg-slate-100 text-slate-600">#{tag}</span>)}</div></section>
    <aside className="space-y-5"><section className="card"><p className="text-xs font-bold text-slate-400">活动发起人</p><h2 className="mt-2 text-lg font-black text-ink">{creator?.nickname ?? "未知同学"}</h2><p className="mt-1 text-sm text-slate-500">{creator?.college} · {creator?.grade}</p><div className="mt-3 flex flex-wrap gap-1">{creator?.interests.map((x) => <span className="tag bg-lavender text-brand" key={x}>{x}</span>)}</div></section><section className="card"><h2 className="font-black text-ink">已加入成员</h2><div className="mt-3 space-y-3">{members.map((member) => member && <div key={member.id} className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-indigo-100 font-black text-brand">{member.nickname.slice(0, 1)}</span><div><p className="text-sm font-bold">{member.nickname}{member.id === activity.creatorId && <span className="ml-2 text-xs text-brand">发起人</span>}</p><p className="text-xs text-slate-500">{member.college}</p></div></div>)}</div></section></aside></div>
    <section className="card mt-5"><h2 className="text-lg font-black text-ink">加入这个活动</h2>{error && <p className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-600">{error}</p>}{!currentUser ? <p className="mt-3 text-sm text-slate-500">登录后即可申请加入。<button className="ml-2 font-bold text-brand" onClick={() => router.push("/login")}>去登录</button></p> : activity.status === "cancelled" ? <p className="mt-3 text-sm text-slate-500">该活动已取消。</p> : isCreator ? <div className="mt-3 flex flex-wrap gap-3"><p className="flex-1 text-sm text-slate-500">你是发起人，可在“我的组队”处理申请。</p><button className="btn-danger" onClick={cancel}>取消活动</button></div> : isMember ? <div className="mt-3 flex flex-wrap gap-3"><p className="flex-1 text-sm text-emerald-600">你已加入，记得准时到达并选择公共地点见面。</p><button className="btn-danger" onClick={leave}>退出活动</button></div> : application ? <p className="mt-3 rounded-2xl bg-lavender p-4 text-sm text-brand">你的申请状态：<b>{application.status === "pending" ? "等待发起人审核" : application.status === "accepted" ? "已通过" : "未通过"}</b></p> : free <= 0 ? <p className="mt-3 text-sm text-rose-600">该活动目前已满员。</p> : <form className="mt-3 flex flex-col gap-3 sm:flex-row" onSubmit={submit}><input className="field flex-1" value={message} onChange={(e) => setMessage(e.target.value)} maxLength={100} placeholder="简单介绍一下自己或说明参与意愿（可选）" /><button className="btn-primary whitespace-nowrap">提交申请</button></form>}</section></main>;
}
